title: Erik Gahlin's Blog 
email: erik.gahlin@oracle.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about JDK Flight Recorder, OpenJDK and Java.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://egahlin.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: thelehhman/plainwhite-jekyll
plugins:
  - jekyll-feed
  - jekyll-redirect-from

plainwhite:
  name: Erik Gahlin
  tagline: |
   OpenJDK, JDK Flight Recorder
  date_format: "%b %-d, %Y"

  social_links:
    twitter: ErikGahlin
    github: flight-recorder

  navigation:
    - title: Posts
      url: "/"
    - title: Documentation
      url: "/documentation"

  portfolio_image:  "assets/duke.jpg"

  sitemap: true

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
